name: CI - Testing GitHub Actions

on:
  workflow_dispatch:

jobs:
  testing_actions:
    runs-on: ubuntu-18.04

    name: Test GitHub Actions

    steps:
      - uses: actions/checkout@v2

      - uses: airvzxf/cache-anything-new-action@main
        id: cache-anything-new-action
        with:
          version: 'v5.21653'
        run: |
          echo "*** Running airvzxf/cache-anything-new-action"

      - uses: actions/upload-artifact@v2
        with:
          name: system_files
          path: ${{ runner.temp }}/system_files*.txt
