name: CI - Testing Cache Anything New | Action

on:
  workflow_dispatch:

jobs:
  testing_actions:
    runs-on: ubuntu-18.04

    name: Testing Actions | Job

    steps:
      - uses: actions/checkout@v2

      # Needs to execute the cache action
      - name: Cache Hello World
        id: cache-hello-world-id
        uses: actions/cache@v2
        with:
          path: cache-hello-world-path
          key: ${{ runner.os }}-cache-hello-world-key-v1.1

      # Implement the cache anything action, add a script which will be executed to be cached.
      - uses: airvzxf/cache-anything-new-action@main
        with:
          version: 'v5.21653'
          script: './install.sh'

      - name: Use the cache
        run: |
          whereis pandoc
          find /home/ -iname hello.txt 2> /dev/null || true
