name: CI - Testing Cache Anything New | Action

on:
  workflow_dispatch:

jobs:
  testing_actions:
    runs-on: ubuntu-18.04

    name: Testing Actions | Job

    steps:
      - env:
          ENV_RUNNER_TEMP: ${{ runner.temp }}
          ENV_SCRIPT_BASE: ${{ github.workspace }}

      - uses: actions/checkout@v2

      - name: Before cache
        run: |
          echo "*** Before cache"
          ls -lhaR "${ENV_RUNNER_TEMP}"
          find /home/ -iname manifest.txt 2> /dev/null || true
          find /home/ -iname cache.tzst 2> /dev/null || true
          find /home/ -iname *prime* 2> /dev/null || true

      - name: Cache Primes
        id: cache-wolf-primes-id
        uses: actions/cache@v2
        with:
          path: cache-wolf-primes-path
          key: ${{ runner.os }}-cache-wolf-primes-key-v1.1

      - name: Generate Prime Numbers
        if: steps.cache-wolf-primes-id.outputs.cache-hit != 'true'
        run: |
          ls -lhaR "${ENV_RUNNER_TEMP}"
          echo "Hello!" > cache-wolf-primes-path
          ls -lha cache-wolf-primes-path
          ls -lha "${ENV_SCRIPT_BASE}"
          find /home/ -iname manifest.txt 2> /dev/null || true
          find /home/ -iname cache.tzst 2> /dev/null || true
          find /home/ -iname *prime* 2> /dev/null || true

      - name: Use Prime Numbers
        run: |
          ls -lha cache-wolf-primes-path
          ls -lhaR "${ENV_RUNNER_TEMP}"
          find /home/ -iname manifest.txt 2> /dev/null || true
          find /home/ -iname cache.tzst 2> /dev/null || true
          find /home/ -iname *prime* 2> /dev/null || true

      - uses: airvzxf/cache-anything-new-action@main
        id: cache-anything-new-action
        with:
          version: 'v5.21653'
          script: './install.sh'

      - name: After cache
        run: |
          echo "*** After cache"
          find /home/ -iname manifest.txt 2> /dev/null || true
          find /home/ -iname cache.tzst 2> /dev/null || true
          find /home/ -iname *prime* 2> /dev/null || true
