name: CI - Testing GitHub Actions

on:
  workflow_dispatch:

jobs:
  testing_actions:
    runs-on: ubuntu-18.04

    name: Test GitHub Actions

    steps:
      - uses: actions/checkout@v2

      - name: Before cache
        run: |
          echo "*** Before cache"

      - uses: airvzxf/cache-anything-new-action@main
        id: cache-anything-new-action
        with:
          identifier: '/bin'
          version: 'v5.21653'
          script: './install.sh'

      - name: After cache
        run: |
          echo "*** After cache"

      - uses: actions/upload-artifact@v2
        with:
          name: system_files
          path: ${{ runner.temp }}/system_files*.txt
