name: CI - Testing Cache Anything New | Action
on:
  workflow_dispatch:

jobs:
  testing_actions:
    name: Testing Actions | Job
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      # Needs to execute the cache action
      - name: Step -> Cache Hello World
        id: cache-id # This ID will be use in the cache anything action.
        uses: actions/cache@v2
        with:
          path: ${{ runner.temp }}/cache-directory # It always should be start with 'runner.temp'
          key: ${{ runner.os }}-cache-hello-world-key-v1.6

      # Implement the cache anything action, add a script which will be executed to be cached.
      # TODO: is_cached -> Try the steps[*] and see if it retrieve the correct steps. Added more cache steps before and after to validate that it's taking the correct.
      - name: Step -> Cache anything
        uses: airvzxf/cache-anything-new-action@main
        with:
          script: './install.sh'
          snapshot: './'
          is_cached: ${{ steps.cache-id.outputs.cache-hit }} # Cache ID, check if the cache was hit.
          temporal: ${{ toJson(steps) }}

      - name: Step -> Use the cache
        run: |
          pwd
          ls -lha "${{ runner.temp }}"
          find /home/ -iname hello.txt 2> /dev/null || true
          whereis pandoc || true
