name: CI - Testing Cache Anything New | Action
on:
  workflow_dispatch:

jobs:
  testing_actions:
    name: Testing Actions | Job
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      # Needs to execute the cache action.
      #   id: it will be use in the cache anything action.
      #   path: It always should be start with 'runner.temp'.
      - name: Step -> Cache Hello World
        id: cache-id
        uses: actions/cache@v2
        with:
          path: ${{ runner.temp }}/good-cache-example
          key: ${{ runner.os }}-cache-hello-world-key-v1.6

      # Implement the cache anything action, add a script which will be executed to be cached.
      #   is_cached: Use the previous cache action id's.
      - name: Step -> Cache anything
        uses: airvzxf/cache-anything-new-action@main
        with:
          script: './install.sh'
          is_cached: ${{ steps.cache-id.outputs.cache-hit }}
          cache: 'good-cache-example'
          snapshot: '/'

      - name: Step -> Use the cache
        run: |
          pwd
          ls -lha "${{ runner.temp }}"
          find /home/ -iname hello.txt 2> /dev/null || true
          whereis pandoc || true
