name: CI - Testing Cache Anything New | Action

on:
  workflow_dispatch:

jobs:
  testing_actions:
    runs-on: ubuntu-18.04

    name: Testing Actions | Job

    steps:
      - uses: actions/checkout@v2

      - name: Before cache
        run: |
          echo "*** Before cache"

      - uses: airvzxf/cache-anything-new-action@main
        id: cache-anything-new-action
        with:
          version: 'v5.21653'
          script: './install.sh'

      - name: After cache
        run: |
          echo "*** After cache"
